name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Flutter 3.29.0 using subosito/flutter-action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      # Cache Pub packages to speed up builds
      - name: Cache Flutter Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter static analysis
      - name: Analyze Code
        run: flutter analyze

      # Run tests
      - name: Run Tests
        run: flutter test

      # Build a release APK (you can adjust this command as needed)
      - name: Build Release APK
        run: flutter build apk --release
