name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter using a GitHub Action
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # Update this version as needed

      # Cache Flutter and Pub packages to speed up builds
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter static analysis
      - name: Analyze Code
        run: flutter analyze

      # Run tests
      - name: Run Tests
        run: flutter test

      # Build a release APK (adjust to your needs)
      - name: Build APK (Release)
        run: flutter build apk --release
