name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 1. Setup Java 17 (required for Android SDK 35+)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # 2. Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 3. Setup Flutter with specific channel
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      # 4. Cache improvements (add Gradle cache)
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml', '**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # 5. Accept Android licenses
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses

      # 6. Install dependencies with fix for Maven Central
      - name: Install Dependencies
        run: |
          flutter pub get
          cd android && ./gradlew --stop && cd ..

      # 7. Build with increased memory and retries
      - name: Build Release APK
        run: |
          flutter build apk --release \
            --dart-define=CI=true \
            --verbose
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Xmx4096m"
